#!/bin/sh
# file /etc/rc.d/init.d/domainManager
# description: domain manager server
# processname: domainManager
#
# Environment variable setting
export DOMAINMANAGER_HOME=/etc/domainManager
#
# See how we were called

case "$1" in
        start)
                echo "Starting DomainManager Server ... "
                bash $DOMAINMANAGER_HOME/.domain_startup.sh
                echo
                ;;
        stop)
                echo "Shutting down DomainManager Server ... "
                bash $DOMAINMANAGER_HOME/.domain_stop.sh
                echo
                ;;
        status)
                pids=$(ps | grep "domainMa" | awk '{print $1}')
                pid=($pids)

                if [ -n "${pid}" ]; then
                        echo "DomainManager Server is running ..."
                else
                        echo "DomainManager Server is not running ..."
                fi
                ;;
        reset)
                echo "Resetting DomainManager Server ... "
                bash $DOMAINMANAGER_HOME/.domain_reset.sh
                echo
                ;;
        restart)
                $0 stop
                sleep 3
                $0 start
                ;;
        *)
                echo "Usage: service domainManager {start|stop|status|reset|restart}"
esac
exit 0
